### ISSUE TITLE
Something is broken

### ISSUE THREAD

**Issue by Zigfrid87** [p2or/blender-loom#102]
Hello. it was working before but a month later it doesn't. something has happened.
I run it (try to run for now) on my Mac Apple Silicon M1

```shell
ERROR (bpy.rna): source/blender/python/intern/bpy_rna.c:7242 pyrna_srna_ExternalType: incorrect subclassing of SRNA 'WindowManager', expected ' ref=3, ptr=0x13148b2f0, type=bpy_struct_meta_idprop, value=<class 'bpy.types.ID'>', see bpy_types.py
Exception in thread Thread-2 (check_for_new_assets):
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.6/python/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Applications/Blender.app/Contents/Resources/3.6/python/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/troevmachine/Library/Application Support/Blender/3.6/scripts/addons/polyhavenassets-main/utils/check_for_new_assets.py", line 17, in check_for_new_assets
    context.window_manager.pha_props.new_assets = 0
AttributeError: 'WindowManager' object has no attribute 'pha_props'

Blender quit
```

**Comment by Zigfrid87** [comment]
Thanks 4 your attention and answer. The fun thing is that I not only disable polyhaven asset I even created a new empty project and tried to render a couple of frames of default cube with loom. but terminal shows me the same errors.
.
Everything was alright before I started to work with comfyUI and it forced me to do a lot of things with python on my machine to install it and to make things run properly. Its obvious I've broken something with my own hands but its hard for me to figure out what exactly it is

**Comment by p2or** [comment]
Hi @Zigfrid87,

> It doesn't fix but it changes the error)) So I'm on my way.

Great! 

> To be honest I really don't have such a directory but why loom even try to find it?! where does it take this directory and why does he try to find it?

_Loom_ just automates the process of [command line rendering](https://docs.blender.org/manual/en/latest/advanced/command_line/render.html) and renders the blend _as is_, means what you see here is the regular output from Blender while starting the rendering. If you were to render the file with the terminal and *without Loom*, you would get the same error - just give it a whirl by opening up a terminal, execute Blender and render a single frame:

```shell
blender -b file.blend -f 10
```

In your case:

```shell
/Applications/Blender.app/Contents/MacOS/Blender -b /path/to/your/file.blend -f 10
```

Also for debugging, might be a big help to see what happens when you start Blender using the terminal. Are there errors right from the start? 

```shell
/Applications/Blender.app/Contents/MacOS/Blender
```

Does this help?

Cheers,
Christian

**Comment by Zigfrid87** [comment]
Hello and thank you. I repaired it in much easier way. I just resaved the project with the another directory and it works alright!
