### ISSUE TITLE
Feature Request: Render frame range backwards

### ISSUE THREAD

**Issue by RyLo2797** [p2or/blender-loom#14]
This is a bit of a niche feature request, but I'd like to be able to input a frame range (i.e. 2053-2000) and have loom render the frames in that order. Currently it will render the range correctly, but it always starts at the lowest number.

I'm not sure how you handle video encode, though. Maybe a checkbox or dropdown that says encode video in rendered order or encode video in frame number order.

Thanks! This is an awesome addon and was exactly what I was looking for.

**Comment by p2or** [comment]
Hi @RyLo2797,

technically that's quite simple to implement. However, the output would be the same range and I guess rendering backwards can have impact on rendering times eg. when using motion blur so this should be tested extensively. Could you please provide any real world example why this can be useful? Re Encoding backwards: I don't think [ffmpeg](ffmpeg.org/) is able to do that. At a first glance might be better to create a 'reversed copy' of the clip, see [How to use FFmpeg Command for Reverse Video?](https://video.stackexchange.com/a/17739).

Anyway, I created a [new branch to address that]( https://github.com/p2or/blender-loom/tree/render-reverse-option). Just download the add-on from there and simply add a `r` as the first character to the input field (hope that's ok for now), eg. `r 0-23` in order to render the frames in reverse order. 

Please test and report back!
Cheers,
Christian

**Comment by p2or** [comment]
No feedback, closing for now.
