### ISSUE TITLE
Disabled render image sequence

### ISSUE THREAD

**Issue by Gulliveer** [p2or/blender-loom#16]
![2021-03-23_17h50_40](https://user-images.githubusercontent.com/81264976/112217100-07e16500-8c01-11eb-8077-16b2ab33e216.png)

I can only render image sequences in default cube files. Is there a "not to do" list that I can follow the steps to be able to render?

**Comment by p2or** [comment]
Hi @Gulliveer ,

yeah, this should be mentioned in the documentation, my fault. In production you usually want to comp the renderings anyway and encode them afterwards due to quality loss (max 10bit prores vs 32bit exr) so direct encoding is not supported and never will be. I'd suggest open up the rendered sequence in https://mrviewer.sourceforge.io/ > right click > encode to mp4 or whatever you like. Or use Loom's 'Encode Image Sequence Dialog' which should do it as well. Hope this helps.

Cheers,
Christian
