### ISSUE TITLE
'globals' variable replacement should work on directory name 

### ISSUE THREAD

**Issue by alinsavix** [p2or/blender-loom#18]
Howdy! Awesome addon here. I just ran into one problem -- I frequently want the output *directory* to change based on the global variables, not just the filename (which seems to be the behavior currently). e.g. right now I can do `//output/$BLEND_frame####` as an output name, but I *can't* do `//output/$BLEND/frame####` as a filename, which is how I normally handle my render outputs. If you could make it so this would work, that would be amazing.

Bonus points if you would also have it make any subdirectories needed (so I don't have to create them by hand), but I'd be more than happy if the variable replacement worked for directories at all.

Thanks! <3

**Comment by p2or** [comment]
Hi @alinsavix,

glad the add-on is useful. I knew that this request will come up at some point ;) Theoretically it should work already, we just have to allow it. However, it needs to be tested extensively before any release since this is risky and the rendering might get lost in worst case.

Do you have the time to seriously test it if I would enabled that?

Cheers,
Christian

**Comment by p2or** [comment]
Hi all!

_Loom_ now allows to replace of all occurrences of any global variable in the output path. I created a new dedicated branch and did test the changes extensively but there might still be some bugs. If you have the time please download _loom_ from here: https://github.com/p2or/blender-loom/tree/globals, test it and let us know if you found a bug or whether there is any unexpected behavior, thanks.

Cheers,
Christian

**Comment by p2or** [comment]
Resolved as of #20.
