### ISSUE TITLE
Can't Render Batch in Blender 3.1

### ISSUE THREAD

**Issue by RomansyahAnim** [p2or/blender-loom#30]
Just like a title says.
It can't Render
When I try to add new blend file, new windows batch appear without single blend inserted.
I usually use this featurein 2.79 below and it's working.
Please can you fix it ? This plugin really helping my project 🙏 and not babysitting to 1 blend file to another

**Comment by RomansyahAnim** [comment]
Hello @p2or 

Hmm ,so this problem only happened to me?
When I try to add blend file to the batch, it's coming back like this
https://i.gyazo.com/2c95550d16402f3de4089b7ec36b4976.mp4
"Nothing selected" if I try to add that file
In the video I use 3.1.2 Version blender (I've also tried version 3.0, same problem)
For the Add-ons I use 0.8.6 version. 

BUT! I try my "Old" project file
2.79 below .blend file below and work!
https://i.gyazo.com/69cc3e0b7d9efee9f4b142e6ab2dad11.mp4
I think .blend 3.0+ fail to detect? Or just my blend project is weird?
I have another project I make in 3.0 and it didn't work. so 3.0, 3.1 .blend is the problem I think

Thank you for the reply
Romansyah

**Comment by p2or** [comment]
Hi @RomansyahAnim,

thanks for making the gifs, really helps to understand your issue. My initial guess was that Blender has problems with your rather long file path. However, I re-created the folders, tested everything and it works fine:

![Annotation 2022-06-10 154904](https://user-images.githubusercontent.com/512368/173080153-e4d13c8b-e36b-48f1-8285-01ae72e261b6.png)

 ... and Loom loads each file into the batch dialog as expected:

![Annotation 2022-06-10 160144](https://user-images.githubusercontent.com/512368/173082613-e6e6c95e-ac04-483e-901c-d7c1509e4cd3.png)


So I guess your blender files are buggy somehow. The frames and the name of the scene are read from the file when the file is added to the list. In case that fails,` "Can't read your.blend"` is printed to the console. 

For further investigation I added a new branch. Please remove the current version of loom, download the add-on from here: https://github.com/p2or/blender-loom/tree/batch-load (using the green 'Code' button), extract the archive, install the `loom.py` file and report back whether that's working, thanks.

Also, could you please share one of those files to test?

Cheers,
Christian

**Comment by RomansyahAnim** [comment]
OHH! With the new Add-ons "Batch-load" It can detect my blend file!

![LoomBatchNewVer](https://user-images.githubusercontent.com/107157684/173124652-589a4ccf-a4a8-4dd1-8715-41dae2c954d3.png)

To make sure, I try again use the 0.8.6 version. if my Project fixed or the plugin working.
and still can't Add Blend file if i use old version. 
so it's true that my blend file is buggy

But.. When I trying to Render it the using "cmd.exe blend" / "command line" the windows is crash Like this
![image](https://user-images.githubusercontent.com/107157684/173126564-c12d43fa-a670-47fc-b553-d87463ae156c.png)

I dunno why. But I try to make sure Once again, the windows cmd is cant render or.. once again, my files
So I trying to "Render Image Sequences this time" and it's working like a normal
https://i.gyazo.com/81d0ec9f82c084493d4b80e44289d28d.mp4
but It cant render when "Render using command line"
https://i.gyazo.com/ef063f5022ec99953604176fe56039b7.mp4

This my files if you want to test it
https://drive.google.com/drive/folders/1JHS0iQgcd3yNkAaNbFiJHt3UUqg6aPpM?usp=sharing

One problem solved, and another one coming it.. sorry for making this difficult

Thank you very much

**Comment by p2or** [comment]
Hi @RomansyahAnim,

thanks for providing the files. It turned out that your blend files are corrupted, Blender even prints `not a blend file` onto the console. If I append all collections of each file into a new clean blend file, everything is back to normal:

![Annotation 2022-06-11 173624](https://user-images.githubusercontent.com/512368/173195246-1984dbd3-7c7b-4a80-b72d-482ac570d153.png)

Anyway, with [yesterday's patch](https://github.com/p2or/blender-loom/tree/batch-load) you are nevertheless able to render all your files using _Loom_ (I also tested rendering your files from the [command line](https://docs.blender.org/manual/en/latest/advanced/command_line/render.html) with no problems). Please note that you'd have to set the frame range manually since Blender/Python can not read the ranges from your buggy files:

![Annotation 2022-06-11 175743](https://user-images.githubusercontent.com/512368/173195354-953fad9a-f80a-400c-bf91-cb8d2cb394ca.png)

The warnings you see in the console `PT_RigSettings does not contain...`, `PT_CosmeticSettings does not contain...` and so forth are coming from _another addon_ which is not following the blender conventions and should be updated, hard to guess from the screenshot which one it is though. One of your rigging add-ons maybe...?

I think that's all I can do for you here, closing for now. If something else comes up, just let me know. Hope this helps.

Cheers,
Christian

**Comment by RomansyahAnim** [comment]
Okay :D thank you very much for you help 👏
