### ISSUE TITLE
New feature: Select render engine for output

### ISSUE THREAD

**Issue by Gattung** [p2or/blender-loom#31]
Maybe a useful feature would be an option to select the render engine used for output i.e. sometimes I like to render frames using workbench, to do so I need to go to the render engine for the scene and change it then change it back to eevee or cycles for normal rendering.

Thanks!

**Comment by p2or** [comment]
Hi @Gattung,

thanks for your request. As a dropdown for the regular render dialog? Good news is that there is a branch already to address that for the batch dialog: https://github.com/p2or/blender-loom/tree/render-attribs

<img width="772" alt="Screenshot 2022-07-23 at 01 39 48" src="https://user-images.githubusercontent.com/512368/180581169-5537fc91-eac9-4b0f-829c-2460b5c4593a.png">

I would appreciate any feedback on this. The problem I personally see is that if there is an option to set the engine, the user wants more... setting the resolution, file format etc. and I have not yet found a way to accommodate all that properties onto the panel. Do you have a good idea to solve this?

Cheers,
Christian

**Comment by Gattung** [comment]
I don't, I can lay that out in an image but wouldn't know how to implement it. 
Thanks for the batch dialog version, I will check it out.

T.

**Comment by p2or** [comment]
Hi @Gattung,

good news, I hope. We could leverage Blender's regular 'Preset-System' to store all necessary render settings. I had some time over the weekend to develop a first prototype: https://github.com/p2or/blender-loom/tree/render-presets

<img width="534" alt="Screenshot 2022-12-11 at 18 36 42" src="https://user-images.githubusercontent.com/512368/206920653-6de7400f-f9b0-4382-bce5-085415534c2d.png">

Basically, this allows to set the engine, samples, output path, image properties, etc. and save all settings as a new custom 'preset' *(Properties Header)*. If a preset exists, a new dropdown will appear in the regular 'Render Dialog' when 'Render using Command Line' is turned on, in order to render the scene regardless of the current settings:

<img width="521" alt="Screenshot 2022-12-11 at 18 38 19" src="https://user-images.githubusercontent.com/512368/206921276-28bb5bc0-64ba-4bcd-8e65-4b9963e52bf2.png">

What do you think?

Cheers,
Christian

**Comment by Gattung** [comment]
I think this is a great implementation, using the presets makes sense.  I'm used to using it as only resolution presets but being able to use them as rendering option presets is very useful.

**Comment by p2or** [comment]
Hi @Gattung,

great, glad you like it. As of the [latest commit](https://github.com/p2or/blender-loom/commit/63c2c12c613ad76bed2cdb3cec2cb75a9e8ffb3f), I've added some options to specify which settings to include in each preset, and it's also now possible to override the render settings using the presets for all files in the 'Batch Dialog'. If you have time to [test it](https://github.com/p2or/blender-loom/tree/render-presets), I would appreciate your feedback on the actual implementation and if you still have ideas to improve something please let me know. 

Otherwise, I will test the changes in my spare time and make them available in the next official release (0.8.9).

Cheers,
Christian
