### ISSUE TITLE
Is it possible to fill gaps with copies for image sequences?

### ISSUE THREAD

**Issue by Hammers69** [p2or/blender-loom#32]
Sorry in advance if I've missed something. I see there is a function for this in encoding a sequence, but it would be awesome to have this option, maybe as a utility, to fill the gaps in an image sequence, to be used in other software.

E.g. I want to render .exr files, on 2s primarily with some frame ranges on 1s and 3s. If I could render those frames with loom, then fill the gaps with copies, I could import those image sequences into Resolve for comp, edit and grading.

Thanks for the very cool tools!

**Comment by p2or** [comment]
Hi @Hammers69,

yes, absolutly. Render your frames, open up the *Encode Image Sequence* dialog, set the path and hit *Fill Gaps with Copies*. For more details see the documentation: https://github.com/p2or/blender-loom#encode-image-sequence-dialog-ctrlshiftf9 

Cheers,
Christian

**Comment by Hammers69** [comment]
Ah yes i just saw, but I haven't got that working with .exr sequences, though I did with png. Am I doing something wrong still?

**Comment by p2or** [comment]
Hi @Hammers69,

to make sure, I did a quick test with an exr sequence and I don't see any issue. I rendered only 1, 4 and 6 and filled the gaps with copies:

<img width="668" alt="Screenshot 2022-09-30 at 16 54 20" src="https://user-images.githubusercontent.com/512368/193297997-20e411a1-c651-4ad2-b476-f30ef16b6bde.png">

Make sure 'verify image sequence' is enabled when selecting the image in the file dialog (<kbd>N</kbd>) *or* click the ghost button to analyse the sequence in order to find any gaps the first place. If gaps were found, the button appears:

<img width="662" alt="Screenshot 2022-09-30 at 16 31 45" src="https://user-images.githubusercontent.com/512368/193296574-e96db715-95b9-4ca0-be1f-2543eeefe9ab.png">

Does this help? Otherwise: Is the button not accessable? Or does copying not work? Anyway, I think you are right and I should mention in the documentation that this function also works independently of the encoding.

Cheers,
Christian

**Comment by Hammers69** [comment]
I'll have another try now, thanks @p2or. For me the button wasn't showing up. I'll experiment again and let you know

**Comment by Hammers69** [comment]
Thanks a lot @p2or your explanation above got it all working again. I wasn't clear on the analysis button etc. This is awesome!

**Comment by p2or** [comment]
No problem, glad it works as expected @Hammers69
