### ISSUE TITLE
Render Selected Keyframes limited to selected object/rig/action, not dopesheet keyframes

### ISSUE THREAD

**Issue by Hammers69** [p2or/blender-loom#34]
I guess this might fall into the 'feature request' pile, but sharing in any case...

I think a lot of my problems getting the correct frames from 'Render Selected Keyframes' have stemmed from this issue. 

It would be great if the selected keyframes in the Dope Sheet could be extracted via 'Render Selected Keyframes' without the objects themselves being necessarily selected. For example in a scene involving lots of props, character, cameras etc. It would be awesome to just select the keyframes via the Dope Sheet summary, to be sure and catch all keys in the shot, even if an object or rig isn't explicitly selected. 

I hope this is a possible thing!

Many thanks again,

Stephen.

**Comment by p2or** [comment]
Hi @Hammers69,

many thanks for bringing that up. I am not quite sure what exactly happened here and I guess this rather falls into the 'bug' pile since selecting any object in the scene shouldn't be necessary to get the keyframes selected and this wasn't intended. I changed the behavior for a reason at some point but obviously did not test the changes sufficiently, I guess.

Anyway, it should now work as intended. By default, you don't have to select an object, and you can optionally limit the keyframes in the selection by enabling the 'Limit to Selection' toggle to the left. You also have the option to hold down <kbd>Ctrl</kbd> when clicking 'Render selected Keyframes' button without any object selected, this will add all keyframes in the scene to the list no matter what's selected. If you hold down <kbd>Alt</kbd> and <kbd>Ctrl</kbd> when clicking 'Render selected Keyframes' button without any object selected, all keyframes in the scene range will be added.

If you have the time, please download Loom from here: https://github.com/p2or/blender-loom/tree/scene_frames and report back, thanks.

Cheers,
Christian

**Comment by p2or** [comment]
Hi @Hammers69,

due to this embarrassing bug, I couldn't wait any longer to merge the [new branch](https://github.com/p2or/blender-loom/tree/scene_frames) with the master. I would still appreciate any kind of feedback if you have time. Thanks again for bringing this up.

Cheers,
Christian

**Comment by Hammers69** [comment]
Ah I just saw this Christian! Thanks so much and I look forward to trying out the update as soon as I can
