### ISSUE TITLE
is it possible to automatically increase the version for every rendered image?

### ISSUE THREAD

**Issue by luckychris** [p2or/blender-loom#36]
I really enjoy using Loom and it works great.
I am just not sure wether i didn't find that feature or whether is isn't here: if i render an image, i would like to save the next image with a new name (although it is the same frame), so e.g. a version number which automatically increases for each image would be great.
Maybe that's already possible?
Thanks, have a great day,
Christoph

**Comment by p2or** [comment]
Hi @luckychris,

thanks, glad it's useful to others too... You can use all kinds of python expressions as part of the output path. Have a look into the 'globals section' in the add-on preferences, there you will find some predefined variables for the `viewlayer`, `camera`, `lens` etc. that serve as a demo. 

For example, if you want to increase the version per frame, you can assign `"v{:04d}".format(bpy.context.scene.frame_current)` to a custom variable of your choice like `$VRSN` or something and use it in the output path like so `//render/your_filename_$VRSN_` which will resolve to `/Users/<user>/Desktop/render/your_filename_v<frame>_####".ext` if the blend is saved on your desktop.

However, you can not get rid of the frame number at the end of the file path if that's your question. Does this help?

Cheers,
Christian

**Comment by luckychris** [comment]
I am sorry, looks like my question wasn't clear enough. I want to be sure that i have always a new name for my rendered file although it is the same frame, blend file etc. That's why i had the idea using version which (maybe) could automatically increase...?

**Comment by p2or** [comment]
Hi @luckychris,

since you can use python expressions as part of the output path, there are many possibilities. For a unique file name, I would personally use the current timestamp, e.g: `exec("import time") or time.strftime("%Y%m%d-%H%M%S")` will resolve to `20221108-080355` and makes it a valid name for all operating systems. 

And in case you didn't noticed, Loom comes with a [version slider](https://github.com/p2or/blender-loom#render-version) as part of the 'Output' panel which I guess you can modify and read using expressions too. Does this help?

Cheers,
Christian

**Comment by luckychris** [comment]
Hi Christian,

you are totally right.
, that's a good idea. Thanks for taking your time to answer me. 

Have great day,
Christoph
