### ISSUE TITLE
File Path Variables apply automatic

### ISSUE THREAD

**Issue by gitingwar** [p2or/blender-loom#37]
Realy nice addon, Thx! 

I propose to introduce the ability to automatically save the render (F12) to the path specified using global variables.
Now path in compositor->output_node after pressing **F12** leads to saving the file in C:\$BLEND\$CAMERA\ (OS: windows) without replacing global variables in path-string
![image](https://user-images.githubusercontent.com/102683439/202374022-e6705bd0-225f-42bc-9c7e-9c4cec07c01a.png)

I understand that you can press the button "**Bake Globals**" ( bpy.ops.loom.globals_bake(action='APPLY') ), but in Scene more cameras and I would like to have this function to replace global variables by default or optionally included in the settings of the scene or addon.

Blender versions: 2.92, 3.1, 3.3 

Thanks! Igor

**Comment by p2or** [comment]
Hi @gitingwar,

thanks for your feedback. But the replacement works when you render using Loom (<kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>F12</kbd>), right? If this does not work, please let me know. In my tests, everything has worked so far.

In general I would not like to change regular operations which interfere with regular operations like <kbd>F12</kbd> in Blender, I'm worried that this might confuse the user and you would have to disable the add-on in case you want to use the old regular <kbd>F12</kbd> function instead of Loom. But you are right of course, there should be at least a hint or a popup appear when variables are used like in this case and an option to use Loom. If you have an idea of what this might look like, please let me know, all ideas are welcome.

Cheers,
Christian

**Comment by gitingwar** [comment]
Hi! `Ctrl+Shift+F12` work correctly.
I`m about this: in standart output property insert checkbox, who enabled looms globals in all paths with F12 render
![image](https://user-images.githubusercontent.com/102683439/203943948-74d81f70-dbe2-4612-afa9-a1f9b18ae58f.png)


In our pipline has local works, local network works and network-render by local network. `Globals `vital for almost any scene in tuning scenes and production by net-render

**Comment by p2or** [comment]
Hi @gitingwar,

good to know this works and thanks for your quick mockup. Just to make sure I understand your request correctly: 

- The file path must be baked because you are rendering on a (custom) render farm on which *Loom* can not be installed? Did you already tried Loom's [batch render](https://github.com/p2or/blender-loom#loom-batch-dialog-ctrlshiftaltf12) functionality on your farm?
- Or would you like to have the functionality on the regular hotkey because you are afraid that employees will accidentally press <kbd>F12</kbd> instead of <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>F12</kbd>?

Cheers,
Christian

**Comment by gitingwar** [comment]
The beauty of using global variables is not to bake any paths. My workflow for my net-render:
1. create scene, in `standart output` path write path with looms globals (`standart output` save jpg for prev)
2. in `compositor` use fileoutput (exr) with path string: `$DEF_OUTPUT_PATH` (variable added in Loom preferences)
3. save net-task for my net-render (many computers in local network without phisic access). i`m added into net-render Looms globals

And yes, the idea of replacing the `CTRL+F12` key is quite working. 
Thanks for you time!
