### ISSUE TITLE
Command Line Render : GRU functions for drawing error.

### ISSUE THREAD

**Issue by samokhin-90** [p2or/blender-loom#48]
![image](https://user-images.githubusercontent.com/34568966/227769339-5c919c36-9275-4f64-a5f9-3ec4077e7549.png)

[blender.crash.txt](https://github.com/p2or/blender-loom/files/11071301/blender.crash.txt)

Updated to version 0.8.9
Redner via the command line stopped working. Can you help me what's wrong here?

**Comment by p2or** [comment]
Hi @samokhin-90,

I try my best to break it down and help you out. I know it's a bit hard to read, but first of all your _color management config_ seems wrong and your current Blender version doesn't support the following add-ons installed:

- The first error is coming from `Exr_Auto_Pass_Saver_Panel` add-on (which should be updated)
- The second error is coming from the `Octane` add-on (which should be updated)
- The third error is coming from `X-Ray selection tools` (which should be updated)

Blender finally crashes because of `Octane` as you can see at the end of you crash log. Unfortunately I do not have access to `Octane` but I'd suggest disable or update these add-ons and report back. 

However, none of these errors are directly related to _Loom_ so I guess there is not much I can do for you here. Does that help you anyway?

Cheers,
Christian

**Comment by p2or** [comment]
Hi @samokhin-90,

you're welcome, I'm glad it's working now. Thanks for keeping me posted.

Cheers,
Christian
