### ISSUE TITLE
Encoding - "PNG Not Supported" warning 

### ISSUE THREAD

**Issue by jansem1** [p2or/blender-loom#53]
I have an image sequence I'm trying to render 
Error:
![image](https://github.com/p2or/blender-loom/assets/59934002/e41392ea-e585-4aa3-99e6-27844cb8b280)

- I am on windows 10
- I have ffmpeg installed and the path set in Loom preferences. I have restarted blender.
  - I have directed the path to the /ffmpeg/, /ffmpeg/bin/, and ~/bin/ffmpeg.exe but they all throw the same error.
  - My ffmpeg path is C:\ffmpeg-2023-06-11-git-09621fd7d9-full_build - Do I need to rename the directory to just 'ffmpeg' or does it not matter?
- I have verified in command prompt that ffmpeg is installed and that .png is an available format via` ffmpeg -encoders and ` and `ffmpeg -codecs`
  - zlib is also an available encoder. I've read that zlib not being installed can cause ffmpeg to not recognize .pngs, but that's not the case here.
    ![image](https://github.com/p2or/blender-loom/assets/59934002/4bc2fbf2-1c8f-4bb3-b326-91e77e43b601)

Output settings:
![image](https://github.com/p2or/blender-loom/assets/59934002/77754346-cb04-432e-bc9b-4a4416ca6821)
- I tried this with the File Format set to .png as well and it throws the same error

Encode image sequence settings:
![image](https://github.com/p2or/blender-loom/assets/59934002/3634b420-2cd0-4b33-9ec6-6640a7ea8fa4)

P.S. This toolset is amazing. It has single-handedly saved a project I've been working on for two months, and I expect to be getting a lot of use out of it on future projects. Thanks so much for making it!

**Comment by p2or** [comment]
Hi @jansem1,

many thanks for your kind words and your detailed report. I'm glad to hear it's useful to others as well.

Yeah, this should be explicitly mentioned in the documentation, sorry about that. As the warning you receive suggests, _Loom_ does not support encoding `png` sequences for several reasons, mainly because `png` has serious issues when it comes to alpha channels and color management. I simply cannot guarantee that the actual output is _always_ correct and I honestly don't want to waste my spare time in maintaining that file format, since I personally don't use it in production.

Anyway, I created a [new branch to address this issue](https://github.com/p2or/blender-loom/tree/encode-png), removed that _Loom_ blocks the execution in this case and introduced a better warning message. Just download _Loom_ using the green code button [over there](https://github.com/p2or/blender-loom/tree/encode-png), reinstall and please report back if you have the time. If more people are interested, we can "enable" or "allow" this permanently and in best case perhaps someone can be found who wants to take care of this. 

What do you think? Does this help?

Cheers,
Christian

**Comment by jansem1** [comment]
That fixed it, thank you so much!
