### ISSUE TITLE
Octane - Suddenly Batch not working (Windows)

### ISSUE THREAD

**Issue by protovu** [p2or/blender-loom#59]
Generally, Loom has been terrific. Love it.
But of late, Batch has stopped working.
I use Blender with Octane. 
The files do render without Loom, so I suppose they are solid files.
A message has been generated: "Octane has tried to start multiple times",Which is odd, as Octane is running pre Batch launch.
Any guidance appreciated.
Win10, 2 Nvidia 3080s

**Comment by p2or** [comment]
Hi @protovu,

glad that the add-on is useful for others as well and thanks for your report. 

A few months ago, there was already a similar report and it turned out that the issue was caused by a lack of administrator rights on Windows (for reasons only to Otoy knows), see https://github.com/p2or/blender-loom/issues/48#issuecomment-1484932589

Does that solve your problem yet? Unfortunately, I don't have access to Octane, so I can't test it at the moment.

Cheers,
Christian

**Comment by p2or** [comment]
Just had the chance to test Octane X™ Prime for Blender (OctaneRender v27.17 addon) on macOS and there are no issues when rendering via command line and everything works as expected as far as I can tell.
