### ISSUE TITLE
All items are greyed out.

### ISSUE THREAD

**Issue by Ulf3000** [p2or/blender-loom#98]
Hi i cannot get the the addon to work anymore. 
All the mneu items are greyed out and operators are missing too as it seems. 
No amount of restarting and saving preferences helps. Im trying with different versions of blender 4.0 and 4.1

**Comment by p2or** [comment]
Hi @Ulf3000,

unfortunately hard to help based on nothing, hence the usual questions to get started: 

- What version of _Loom_ are you using?
- What version of _Blender_ are you using? 
- Does it work with _LTS_ versions (Blender 3.6, Blender 4.2) on your machine?
- What _OS_ are you using?
- ...

And the most important question: Is there any output in the _System Console_? Please consider that I have to reproduce your bug (if there is one) on my machine in order to fix it and I do this in my spare time, so please take your time and put a bit more effort into this, thanks.

Cheers,
Christian

PS, It is rarely necessary to restart Blender, in order to reload your add-ons and see potential issues, you can go to _System > Reload Scripts_ (and report back).

**Comment by Ulf3000** [comment]
sorry i just had mp4 as rendering format in my file that i loaded... setting it to png solved the issue, i wasted hours on this 😭 sorry for troubling you.

**Comment by p2or** [comment]
Hi @Ulf3000,

no problem - glad it's working. We could add a dedicated dialog along with a warning that video is not supported, but _graying out the operators_ complies with the guidelines of Blender and there is already a warning in the path preview:

![Screenshot 2024-10-16 at 08 27 16](https://github.com/user-attachments/assets/f3f377d8-c343-4acd-84e1-6c23ea5f236d)

If you have a better idea, just let me know.

Cheers,
Christian
